    export {
        API_URL, COMPANY_COUPON_GET_PAGED_SORTED_URL,
        ADMIN_LOGIN_URL, COMPANY_COUPON_GET_EXAMPLE_URL,
        COMPANY_LOGIN_URL, COUPON_DELETE_URL,
        CUSTOMER_LOGIN_URL, COMPANY_COUPON_GET_ALL_URL,
        COMPANY_LOAD_URL, CUSTOMER_COUPON_GET_ALL_URL,
        CUSTOMER_LOAD_URL, CUSTOMER_COUPON_GET_PAGED_URL,
        CATEGORY_POST_URL, CUSTOMER_COUPON_GET_PAGED_SORTED_URL,
        CATEGORY_PUT_URL, COUPON_GET_PAGED_URL,
        ADMIN_CATEGORY_GET_ALL_URL, COUPON_GET_PAGED_SORTED_URL,
        CATEGORY_DELETE_URL, COUPON_GET_EXAMPLE_URL,
        COMPANY_POST_URL, PAGE_INDEX, COMPANY_CATEGORY_GET_ALL_URL,
        COMPANY_PUT_URL, PAGE_SIZE, CUSTOMER_CATEGORY_GET_ALL_URL,
        COMPANY_GET_ALL_URL, SORT_TYPE, CUSTOMER_COUPON_GET_URL,
        COMPANY_DELETE_URL, SORT_DIRECTION, COUPON_PURCHASE_URL,
        COMPANY_GET_URL, RESULTS_COUNT,
        COMPANY_GET_PAGED_URL, NAME_EXAMPLE,
        COMPANY_GET_PAGED_SORTED_URL,
        COMPANY_GET_EXAMPLE_URL,
        CUSTOMER_POST_URL,
        CUSTOMER_PUT_URL,
        CUSTOMER_GET_ALL_URL,
        CUSTOMER_DELETE_URL,
        CUSTOMER_GET_URL,
        CUSTOMER_GET_PAGED_URL,
        CUSTOMER_GET_PAGED_SORTED_URL,
        CUSTOMER_GET_EXAMPLE_URL,
        COUPON_POST_URL,
        COUPON_PUT_URL,
        COMPANY_COUPON_GET_URL,
        COMPANY_COUPON_GET_PAGED_URL,
        CUSTOMER_COUPON_GET_EXAMPLE_URL,
        AUTH_URL
     }
    
    const API_URL = 'http://localhost:8080/coupersb/';

    const LOGIN = 'login';
    const GET_DETAILS = 'getDetails';
    const ADD = 'add';
    const UPDATE = 'update';
    const GET = 'get/';
    const DELETE = 'delete/';
    const ALL = 'all';
    const PAGED = 'paged';
    const PAGE_SORTED = 'pagedSorted';
    const EXAMPLE = 'example';

    const ADMIN_URL = API_URL + 'admin/';
    const COMPANY_URL = API_URL + 'company/';
    const CUSTOMER_URL = API_URL + 'customer/';

    const ADMIN_LOGIN_URL = ADMIN_URL + LOGIN;
    const COMPANY_LOGIN_URL = COMPANY_URL + LOGIN;
    const CUSTOMER_LOGIN_URL = CUSTOMER_URL + LOGIN;

    const COMPANY_LOAD_URL = COMPANY_URL + GET_DETAILS;
    const CUSTOMER_LOAD_URL = CUSTOMER_URL + GET_DETAILS;

    const ADMIN_CATEGORY_URL = ADMIN_URL + 'category/';
    const COMPANY_CATEGORY_URL = COMPANY_URL + 'category/';
    const CUSTOMER_CATEGORY_URL = CUSTOMER_URL + 'category/';
    const CATEGORY_POST_URL = ADMIN_CATEGORY_URL + ADD;
    const CATEGORY_PUT_URL = ADMIN_CATEGORY_URL + UPDATE;
    const ADMIN_CATEGORY_GET_ALL_URL = ADMIN_CATEGORY_URL + GET + ALL;
    const COMPANY_CATEGORY_GET_ALL_URL = COMPANY_CATEGORY_URL + GET + ALL;
    const CUSTOMER_CATEGORY_GET_ALL_URL = CUSTOMER_CATEGORY_URL + GET + ALL;
    const CATEGORY_DELETE_URL = ADMIN_CATEGORY_URL + DELETE;

    const COMPANY_ADMIN_URL = ADMIN_URL + 'company/';
    const COMPANY_POST_URL = COMPANY_ADMIN_URL + ADD;
    const COMPANY_PUT_URL = COMPANY_ADMIN_URL + UPDATE;
    const COMPANY_GET_URL = COMPANY_ADMIN_URL + GET;
    const COMPANY_GET_ALL_URL = COMPANY_GET_URL + ALL;
    const COMPANY_GET_PAGED_URL = COMPANY_GET_URL + PAGED;
    const COMPANY_GET_PAGED_SORTED_URL = COMPANY_GET_URL + PAGE_SORTED;
    const COMPANY_GET_EXAMPLE_URL = COMPANY_GET_URL + EXAMPLE;
    const COMPANY_DELETE_URL = COMPANY_ADMIN_URL + DELETE;

    const CUSTOMER_ADMIN_URL = ADMIN_URL + 'customer/';
    const CUSTOMER_POST_URL = CUSTOMER_ADMIN_URL + ADD;
    const CUSTOMER_PUT_URL = CUSTOMER_ADMIN_URL + UPDATE;
    const CUSTOMER_GET_URL = CUSTOMER_ADMIN_URL + GET;
    const CUSTOMER_GET_ALL_URL = CUSTOMER_GET_URL + ALL;
    const CUSTOMER_GET_PAGED_URL = CUSTOMER_GET_URL + PAGED;
    const CUSTOMER_GET_PAGED_SORTED_URL = CUSTOMER_GET_URL + PAGE_SORTED;
    const CUSTOMER_GET_EXAMPLE_URL = CUSTOMER_GET_URL + EXAMPLE;
    const CUSTOMER_DELETE_URL = CUSTOMER_ADMIN_URL + DELETE;

    const COMPANY_COUPON_URL = COMPANY_URL + 'coupon/';
    const COUPON_POST_URL = COMPANY_COUPON_URL + ADD;
    const COUPON_PUT_URL = COMPANY_COUPON_URL + UPDATE;
    const COMPANY_COUPON_GET_URL = COMPANY_COUPON_URL + GET;
    const COMPANY_COUPON_GET_ALL_URL = COMPANY_COUPON_GET_URL + ALL;
    const COMPANY_COUPON_GET_PAGED_URL = COMPANY_COUPON_GET_URL + PAGED;
    const COMPANY_COUPON_GET_PAGED_SORTED_URL = COMPANY_COUPON_GET_URL + PAGE_SORTED;
    const COMPANY_COUPON_GET_EXAMPLE_URL = COMPANY_COUPON_GET_URL + EXAMPLE;
    const COUPON_DELETE_URL = COMPANY_COUPON_URL + DELETE;
     
    const CUSTOMER_COUPON_URL =  CUSTOMER_URL + 'coupon/';
    const CUSTOMER_ALLCOUPONS_URL = CUSTOMER_URL + "allCoupon/";
    const CUSTOMER_ALL_COUPON_GET_URL = CUSTOMER_ALLCOUPONS_URL + GET;
    const CUSTOMER_COUPON_GET_URL = CUSTOMER_COUPON_URL + GET;
    const CUSTOMER_COUPON_GET_ALL_URL = CUSTOMER_COUPON_GET_URL + ALL;
    const CUSTOMER_COUPON_GET_PAGED_URL = CUSTOMER_COUPON_GET_URL + PAGED;
    const CUSTOMER_COUPON_GET_PAGED_SORTED_URL = CUSTOMER_COUPON_GET_URL + PAGE_SORTED;
    const CUSTOMER_COUPON_GET_EXAMPLE_URL = CUSTOMER_COUPON_GET_URL + EXAMPLE;

    const COUPON_GET_PAGED_URL = CUSTOMER_ALL_COUPON_GET_URL + PAGED;
    const COUPON_GET_PAGED_SORTED_URL = CUSTOMER_ALL_COUPON_GET_URL + PAGE_SORTED;
    const COUPON_GET_EXAMPLE_URL = CUSTOMER_ALL_COUPON_GET_URL + EXAMPLE;

    const COUPON_PURCHASE_URL = CUSTOMER_COUPON_URL + 'purchase';

    const AUTH_URL = API_URL + 'authenticated';

    const PAGE_INDEX = 'pageIndex';
    const PAGE_SIZE = 'pageSize';
    const SORT_TYPE = 'sortBy';
    const SORT_DIRECTION = 'asc';
    const RESULTS_COUNT = 'resultsCount';
    const NAME_EXAMPLE = 'nameExample';



